apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpiconsumer
spec:
  selector:
    matchLabels:
      app: bpiconsumer
  template:
    metadata:
      labels:
        app: bpiconsumer
    spec:
      containers:
      - name: bpiconsumer
        image: sumyatphyoe/bpiconsumer
        env:
        - name: RABBITMQ_HOST
          value: "Bpi"
        - name: RABBITMQ_PORT
          value: "31672"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: bpiconsumer
spec:
  selector:
    app: bpiconsumer
  ports:
  - port: 80
    targetPort: 5000
